parser: babel-eslint

parserOptions:
  sourceType: module

env:
  es6: true
  jest: true
  node: true

plugins: [react]

extends: [eslint:recommended, plugin:import/errors, plugin:import/warnings, plugin:react/recommended]

rules:
  prefer-arrow-callback: error
  react/display-name: off
